name: Build Android apk detailed
on: [push]
# on:
#   release:
#     types: [published]
#   push:
#     branches:
#       - feature/Longchi/feature3

jobs:
  build:
    # if: contains(github.ref, 'refs/tags/*mobile*') || contains(github.ref, 'refs/branches/*pwa*')
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout source
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 4.10.3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Add Android platform
        run: ionic cordova platform add android@latest

      - name: Build Android Dev APK
        run: ionic cordova build android

      - name: Build Android Release APK
        run: ionic cordova build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./platforms/android/
        run: ./gradlew bundle

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release--aab
          path: platforms/android/app/build/outputs/bundle/release/app.aab
