name: Build Android app

on: [push]
# on:
#   release:
#     types: [published]
#   push:
#     branches:
#       - "feature/Longchi/new-feature1"
#       - "feature/Longchi/new-feature2"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install @angular/cli
        run: npm i -D -E @angular/cli
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 9
      #    - name: Cache NPM dependencies
      #      uses: actions/cache@v1
      #      with:
      #        path: node_modules
      #        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package.json') }}
      #        restore-keys: |
      #          ${{ runner.OS }}-npm-cache-
      - name: Build Android Dev APK
        run: ionic cordova build android

      - name: Build Android Release APK
        run: ionic cordova build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./platforms/android/
        run: ./gradlew bundle

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: platforms/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign Release bundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: platforms/android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload release apk
        uses: actions/upload-artifact@v1
        with:
          name: app-release-apk
          path: platforms/android/app/build/outputs/apk/release/app-release-unsigned-signed.apk

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release-aab
          path: platforms/android/app/build/outputs/bundle/release/app.aab
